apiVersion: apps/v1

kind: Deployment

metadata:
  name: fortune-deployment
  namespace: workshop02

spec:
  replicas: 4
  selector: 
    matchLabels:
      app.kubernetes.io/name: fortune-pod
      app.kubernetes.op/version: "v2"
      
  template:
    metadata:
      name: fortune-pod
      labels:
        app.kubernetes.io/name: fortune-pod
        app.kubernetes.op/version: "v2"
        owner: engineering

    spec:
      containers:
      - name: fortune
        image: james1122/fortune
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            value: "3000"
        ports:
          - name: fortune-port
            containerPort: 3000