---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: bgg-app-deployment
  namespace: workshop02

spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: bgg-app-pod

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      name: bgg-app-pod
      labels:
        app.kubernetes.io/name: bgg-app-pod
        app.kubernetes.op/version: "v2"
#        app.kubernetes.op/version: "v1"
#        owner: engineering
    spec:
      containers:
      - name: bgg-app-container
#        image: stackupiss/bgg-app:v1
        image: stackupiss/bgg-app:v2
        imagePullPolicy: Always
        env:
        - name: APP_PORT
          value: "3000"
        - name: BGG_DB_HOST
          value: "bgg-db-svc.workshop02.svc.cluster.local"
        - name: BGG_DB_PORT
          value: "3306"
        - name: BGG_DB_USER
          value: "root"
        - name: BGG_DB_PASSWORD
          value: "changeit"
        ports:
        - name: bgg-app-port
          containerPort: 3000

---
apiVersion: v1

kind: Service

metadata:
  name: bgg-app-svc
  namespace: workshop02
  labels:
    name: bgg-app-svc

spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: bgg-app-pod
    app.kubernetes.op/version: "v2"
  ports:
  - name: mysql-port-svc
    port: 80
    targetPort: bgg-app-port

